<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #4a5568; padding-bottom: 10px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th { background-color: #4a5568; color: white; padding: 10px; text-align: left; }
        td { border-bottom: 1px solid #edf2f7; padding: 10px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; color: #718096; }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ config('app.name') }} - Books Report</h2>
        <p>Generated: {{ now()->toDayDateTimeString() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($books as $book)
            <tr>
                <td>{{ $book->title }}</td>
                <td>{{ $book->author }}</td>
                <td>{{ $book->status ?? 'Available' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Page generated by Library_SYS_management
    </div>
</body>
</html>
